# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main

pool:
 vmImage: 'ubuntu-latest'

variables:
  imageName: 'bakery-core'
  imageTag: '$(Build.BuildId)'

steps:
- task: UseNode@1
  inputs:
    version: '24.15.0'

- script: |
    corepack enable
    corepack prepare pnpm@latest --activate
  displayName: 'Install pnpm'

- script: |
    pnpm install --no-frozen-lockfile --ignore-scripts
  displayName: 'Install dependencies'

- script: |
    pnpm run build
  displayName: 'Build NestJS project'

#----------------------
  #TAREA 3 DOCKERIZAR
- script: |
    docker build \
      --tag $(imageName):$(imageTag) \
      --tag $(imageName):latest \
      .
  displayName: 'Docker - Construir imagen'
 
- script: |
    docker run -d \
      --name bakery-test \
      -p 3000:3000 \
      $(imageName):latest
    echo "Contenedor iniciado"
  displayName: 'Docker - Ejecutar contenedor'
 
- script: |
    echo "Esperando que la app inicie..."
    sleep 15
    curl --fail http://localhost:3000 && echo "OK - La app responde correctamente"
  displayName: 'Docker - Validar funcionamiento'
 
- script: |
    echo "=== Logs del contenedor ==="
    docker logs bakery-test
    echo ""
    echo "=== Imagen generada ==="
    docker images | grep $(imageName)
    echo ""
    echo "=== Contenedor en ejecucion ==="
    docker ps | grep bakery-test
  displayName: 'Docker - Mostrar estado'
 
- script: |
    docker stop bakery-test
    docker rm bakery-test
  displayName: 'Docker - Limpiar contenedor de prueba'
  condition: always()


# TAREA 1: Enviar los archivos compilados al Droplet
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'digital_ocean_core'
    contents: |
      dist/**
      package.json
      pnpm-lock.yaml
    targetFolder: '/var/www/bakery-core'
    readyTimeout: '30000'

# TAREA 2: Instalar dependencias en el servidor y reiniciar
- task: SSH@0
  inputs:
    sshEndpoint: 'digital_ocean_core'
    runOptions: 'inline'
    inline: |
      # 1. Cargamos el entorno de Node/NVM
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      
      # 2. Ahora que el sistema conoce 'node' y 'pnpm', entramos a la carpeta
      cd /var/www/bakery-core
      
      # 3. Activamos corepack y pnpm
      corepack enable
      corepack prepare pnpm@latest --activate
      
      # 4. Instalamos dependencias de producción
      pnpm install --prod --ignore-scripts
      
      # 5. Reiniciamos con PM2 (asegúrate de que pm2 esté instalado globalmente en el droplet)
      pm2 restart bakery_core || pm2 start dist/main.js --name "bakery_core"
    readyTimeout: '30000'